//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleMessageSender.MessageReceiverService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageReceiverService.MessageReceiverSoap")]
    public interface MessageReceiverSoap {
        
        // CODEGEN: Generating message contract since element name Message from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        ConsoleMessageSender.MessageReceiverService.GetMessageResponse GetMessage(ConsoleMessageSender.MessageReceiverService.GetMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleMessageSender.MessageReceiverService.GetMessageResponse> GetMessageAsync(ConsoleMessageSender.MessageReceiverService.GetMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessage", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleMessageSender.MessageReceiverService.GetMessageRequestBody Body;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(ConsoleMessageSender.MessageReceiverService.GetMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime DateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message;
        
        public GetMessageRequestBody() {
        }
        
        public GetMessageRequestBody(System.DateTime DateTime, string Message) {
            this.DateTime = DateTime;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleMessageSender.MessageReceiverService.GetMessageResponseBody Body;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(ConsoleMessageSender.MessageReceiverService.GetMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessageResult;
        
        public GetMessageResponseBody() {
        }
        
        public GetMessageResponseBody(string GetMessageResult) {
            this.GetMessageResult = GetMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageReceiverSoapChannel : ConsoleMessageSender.MessageReceiverService.MessageReceiverSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageReceiverSoapClient : System.ServiceModel.ClientBase<ConsoleMessageSender.MessageReceiverService.MessageReceiverSoap>, ConsoleMessageSender.MessageReceiverService.MessageReceiverSoap {
        
        public MessageReceiverSoapClient() {
        }
        
        public MessageReceiverSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageReceiverSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageReceiverSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageReceiverSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleMessageSender.MessageReceiverService.GetMessageResponse ConsoleMessageSender.MessageReceiverService.MessageReceiverSoap.GetMessage(ConsoleMessageSender.MessageReceiverService.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public string GetMessage(System.DateTime DateTime, string Message) {
            ConsoleMessageSender.MessageReceiverService.GetMessageRequest inValue = new ConsoleMessageSender.MessageReceiverService.GetMessageRequest();
            inValue.Body = new ConsoleMessageSender.MessageReceiverService.GetMessageRequestBody();
            inValue.Body.DateTime = DateTime;
            inValue.Body.Message = Message;
            ConsoleMessageSender.MessageReceiverService.GetMessageResponse retVal = ((ConsoleMessageSender.MessageReceiverService.MessageReceiverSoap)(this)).GetMessage(inValue);
            return retVal.Body.GetMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleMessageSender.MessageReceiverService.GetMessageResponse> ConsoleMessageSender.MessageReceiverService.MessageReceiverSoap.GetMessageAsync(ConsoleMessageSender.MessageReceiverService.GetMessageRequest request) {
            return base.Channel.GetMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleMessageSender.MessageReceiverService.GetMessageResponse> GetMessageAsync(System.DateTime DateTime, string Message) {
            ConsoleMessageSender.MessageReceiverService.GetMessageRequest inValue = new ConsoleMessageSender.MessageReceiverService.GetMessageRequest();
            inValue.Body = new ConsoleMessageSender.MessageReceiverService.GetMessageRequestBody();
            inValue.Body.DateTime = DateTime;
            inValue.Body.Message = Message;
            return ((ConsoleMessageSender.MessageReceiverService.MessageReceiverSoap)(this)).GetMessageAsync(inValue);
        }
    }
}
